-- ----------------------------
-- Table structure for cur_assets_package_his
-- ----------------------------
DROP TABLE IF EXISTS `cur_assets_package_his`;
CREATE TABLE `cur_assets_package_his` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `org_casNo` varchar(64) NOT NULL COMMENT '机构案件号',
  `org` varchar(20) DEFAULT NULL COMMENT '所属机构',
  `transferType` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `rmb_ye` decimal(20,2) DEFAULT NULL COMMENT '人民币账户余额',
  `rmb_yhfxzje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户应还罚息总额',
  `rmb_yhlizje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户应还利息总额',
  `rmb_yhbjzje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户应还本金总额',
  `rmb_yhfyzje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户应还费用总额',
  `rmb_zdyhje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户最低应还金额',
  `rmb_qkzje` decimal(20,2) DEFAULT NULL COMMENT '人民币账户欠款总金额',
  `borrow_no` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `borrow_blank` varchar(20) DEFAULT NULL COMMENT '借款卡银行',
  `borrow_ed` decimal(20,2) DEFAULT NULL COMMENT '借款额度',
  `rcr` date DEFAULT NULL COMMENT '入催日',
  `fz` varchar(10) DEFAULT NULL COMMENT '分值',
  `area_center` varchar(128) DEFAULT NULL COMMENT '区域中心',
  `max_yqts_his` varchar(10) DEFAULT NULL COMMENT '历史最大逾期天数',
  `sum_yqts_his` varchar(10) DEFAULT NULL COMMENT '历史累计逾期天数',
  `sum_yqcs_his` varchar(10) DEFAULT NULL COMMENT '历史累计逾期次数',
  `ww_city_name` varchar(32) DEFAULT NULL COMMENT '委外城市名称',
  `wa_ye` decimal(20,2) DEFAULT NULL COMMENT '委案余额',
  `bill_address` varchar(500) DEFAULT NULL,
  `year_rates` varchar(20) DEFAULT NULL COMMENT '年利率',
  `tj_firm` varchar(200) DEFAULT NULL,
  `tj_wd` varchar(200) DEFAULT NULL,
  `day_rates` varchar(10) DEFAULT NULL COMMENT '日利率',
  `account_date` varchar(10) DEFAULT NULL COMMENT '账单日',
  `overdue_days` varchar(20) DEFAULT NULL COMMENT '逾期天数',
  `first_yq_date` date DEFAULT NULL COMMENT '首次逾期日期',
  `first_yqjc_date` date DEFAULT NULL COMMENT '首次逾期解除日期',
  `first_yq_flag` varchar(10) DEFAULT NULL COMMENT '首逾标识',
  `cur_name` varchar(64) DEFAULT NULL COMMENT '客户名称',
  `cur_sex` varchar(10) DEFAULT NULL COMMENT '客户性别',
  `certificate_no` varchar(30) DEFAULT NULL COMMENT '证件号码',
  `certificate_address` varchar(500) DEFAULT NULL,
  `regist_address` varchar(500) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `marriage` varchar(10) DEFAULT NULL COMMENT '婚姻状况',
  `education` varchar(10) DEFAULT NULL COMMENT '教育程度',
  `customer_mobile` varchar(50) DEFAULT NULL,
  `customer_home_tel` varchar(50) DEFAULT NULL,
  `customer_home_address` varchar(500) DEFAULT NULL,
  `work_name` varchar(200) DEFAULT NULL,
  `work_address` varchar(500) DEFAULT NULL,
  `work_tel` varchar(50) DEFAULT NULL,
  `first_liaison_name` varchar(20) DEFAULT NULL COMMENT '第一联系人姓名',
  `first_liaison_relation` varchar(20) DEFAULT NULL COMMENT '第一联系人与客户关系',
  `first_liaison_mobile` varchar(50) DEFAULT NULL,
  `first_liaison_tel` varchar(50) DEFAULT NULL,
  `second_liaison_name` varchar(50) DEFAULT NULL COMMENT '第二联系人姓名',
  `second_liaison_relation` varchar(20) DEFAULT NULL COMMENT '第二联系人与客户关系',
  `second_liaison_mobile` varchar(50) DEFAULT NULL,
  `second_liaison_tel` varchar(50) DEFAULT NULL,
  `three_liaison_name` varchar(20) DEFAULT NULL COMMENT '第三联系人姓名',
  `three_liaison_relation` varchar(20) DEFAULT NULL COMMENT '第三联系人与客户关系',
  `three_liaison_mobile` varchar(50) DEFAULT NULL,
  `three_liaison_tel` varchar(50) DEFAULT NULL,
  `cpmc` varchar(64) DEFAULT NULL COMMENT '产品名称',
  `hk_type` varchar(32) DEFAULT NULL COMMENT '还款方式',
  `znj` decimal(20,2) DEFAULT NULL COMMENT '滞纳金',
  `ajhssj` datetime DEFAULT NULL COMMENT '案件回收时间',
  `org_id` varchar(64) DEFAULT NULL COMMENT '机构id',
  `package_flag` char(1) DEFAULT NULL COMMENT '打包标识(0,未打包，1,已打包)',
  `create_by` varchar(32) DEFAULT NULL COMMENT '导入人',
  `create_time` datetime DEFAULT NULL COMMENT '导入时间',
  `close_case` int(1) DEFAULT NULL COMMENT '结案状态0：未结案 1：已结案',
  `is_exit_collect` int(1) DEFAULT NULL COMMENT '是否出催1：是 2：否',
  `import_batch_no` varchar(50) DEFAULT NULL,
  `close_case_date` datetime DEFAULT NULL COMMENT '结案时间',
  `package_id` varchar(64) DEFAULT NULL COMMENT '资产包id',
  `account_age` varchar(64) DEFAULT NULL COMMENT '账龄',
  `la_flag` varchar(20) DEFAULT NULL COMMENT '留案标签',
  `fx_flag` varchar(20) DEFAULT NULL COMMENT '风险标签',
  `htlx` varchar(20) DEFAULT NULL COMMENT '合同类型',
  `jmbq` varchar(20) DEFAULT NULL COMMENT '减免标签',
  `fcbq` varchar(20) DEFAULT NULL COMMENT '法催标签',
  `fxsfbh` varchar(20) DEFAULT NULL COMMENT '罚息是否变化',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `tar` date DEFAULT NULL COMMENT '退案日',
  `jkrq` date DEFAULT NULL COMMENT '借款日期',
  `zhychkr` date DEFAULT NULL COMMENT '最近一次还款日',
  `mqhkje` decimal(20,2) DEFAULT NULL COMMENT '每期还款金额',
  `dqqkje` decimal(20,2) DEFAULT NULL COMMENT '当期欠款金额',
  `ljyhje` decimal(20,2) DEFAULT NULL COMMENT '累计已还金额',
  `sfje` decimal(20,2) DEFAULT NULL COMMENT '首付金额',
  `zdhkzh1` varchar(64) DEFAULT NULL COMMENT '指定还款账号1',
  `zdhkzh2` varchar(64) DEFAULT NULL COMMENT '指定还款账号2',
  `zdhkzhhm1` varchar(64) DEFAULT NULL COMMENT '指定还款账户户名1',
  `zdhkzhhm2` varchar(64) DEFAULT NULL COMMENT '指定还款账户户名2',
  `zdhkqd1` varchar(64) DEFAULT NULL COMMENT '指定还款渠道1',
  `zdhkqd2` varchar(64) DEFAULT NULL COMMENT '指定还款渠道2',
  `khmb` varchar(64) DEFAULT NULL COMMENT '考核目标',
  `spjg` decimal(20,2) DEFAULT NULL COMMENT '商品价格',
  `dklx` varchar(20) DEFAULT NULL COMMENT '贷款类型',
  `jkbs` varchar(20) DEFAULT NULL COMMENT '借款笔数',
  `spxx` varchar(128) DEFAULT NULL COMMENT '商品信息',
  `wacs` varchar(20) DEFAULT NULL COMMENT '委案次数',
  `ykqs` varchar(20) DEFAULT NULL COMMENT '已还期数',
  `work_dept` varchar(64) DEFAULT NULL COMMENT '工作部门',
  `customer_mobile2` varchar(64) DEFAULT NULL COMMENT '客户电话2',
  `customer_mobile3` varchar(64) DEFAULT NULL COMMENT '客户电话3',
  `customer_mobile4` varchar(64) DEFAULT NULL COMMENT '客户电话4',
  `fourth_liaison_name` varchar(64) DEFAULT NULL COMMENT '联系人4姓名',
  `fourth_liaison_relation` varchar(64) DEFAULT NULL COMMENT '联系人4关系',
  `fourth_liaison_mobile` varchar(64) DEFAULT NULL COMMENT '联系人4电话',
  `fifth_liaison_name` varchar(64) DEFAULT NULL COMMENT '联系人5姓名',
  `fifth_liaison_relation` varchar(64) DEFAULT NULL COMMENT '联系人5关系',
  `fifth_liaison_mobile` varchar(64) DEFAULT NULL COMMENT '联系人5电话',
  `dqyhje` decimal(20,2) DEFAULT NULL COMMENT '当前已还金额',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户资产历史表';

-- ----------------------------
-- Table structure for t_lc_call_record_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_call_record_his`;
CREATE TABLE `t_lc_call_record_his` (
  `id` bigint(19) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `contact_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '联系人姓名',
  `phone` varchar(30) DEFAULT NULL COMMENT '电话号码',
  `contact_relation` int(11) DEFAULT NULL COMMENT '和本人关系 1：本人，2：',
  `call_start_time` datetime DEFAULT NULL COMMENT '通话开始时间',
  `call_end_time` datetime DEFAULT NULL COMMENT '通话结束时间',
  `call_len` varchar(19) DEFAULT NULL COMMENT '通话时长',
  `call_sign` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '通话结果标记 1:承诺还款 2:谈判 3:半失连 4:拒绝还款 5:失连',
  `call_result` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '通话结果',
  `call_radio_location` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '通话录音存放位置',
  `call_radio` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '通话录音',
  `create_time` datetime DEFAULT NULL,
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `case_no` varchar(255) DEFAULT NULL COMMENT '案件编号',
  `remark` text COMMENT '备注',
  `platform` varchar(10) DEFAULT NULL COMMENT '所属话务平台：PA、ZJ',
  `find_date` date DEFAULT NULL COMMENT '查账日期',
  `agent_name` varchar(64) DEFAULT NULL COMMENT '坐席名称',
  `star` int(11) DEFAULT '0' COMMENT '关注度',
  `type` int(2) DEFAULT NULL COMMENT '类型，1：打电话下电话码 2：未打电话直接下电话码3：导入催记电话码',
  `make_call_time` datetime DEFAULT NULL COMMENT '拨打时间',
  PRIMARY KEY (`id`),
  KEY `case_no_index` (`case_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1000918335 DEFAULT CHARSET=utf8 COMMENT='通话结果记录历史表';

-- ----------------------------
-- Table structure for t_lc_cust_contact_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_cust_contact_his`;
CREATE TABLE `t_lc_cust_contact_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `certificate_no` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户证件号码',
  `contact_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '联系人姓名',
  `relation` int(100) DEFAULT NULL COMMENT '和本人关系 1：本人，2：直系，3：亲戚，4：朋友',
  `phone` varchar(50) DEFAULT NULL COMMENT '手机号',
  `tel` varchar(50) DEFAULT NULL COMMENT '固定电话',
  `address` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '联系人家庭地址',
  `origin` int(11) DEFAULT NULL COMMENT '联系人数据来源0：资产导入1：页面添加',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL,
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  `validate_status` int(11) DEFAULT '1' COMMENT '是否有效 1：是，2：否',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `org_id` varchar(100) DEFAULT NULL COMMENT '机构编码',
  `org_name` varchar(100) DEFAULT NULL COMMENT '机构名称',
  `import_batch_no` varchar(100) DEFAULT NULL COMMENT '导入批次号',
  `is_close` char(1) DEFAULT '0' COMMENT '是否停拨(0,正常，1,停拨)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63017 DEFAULT CHARSET=utf8 COMMENT='客户联系人信息历史表';

-- ----------------------------
-- Table structure for t_lc_cust_job_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_cust_job_his`;
CREATE TABLE `t_lc_cust_job_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `custom_code` varchar(100) DEFAULT NULL COMMENT '客户编号',
  `certificate_no` varchar(255) DEFAULT NULL COMMENT '客户身份证号',
  `profession` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '职业',
  `company_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '单位名称',
  `company_tel` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '单位电话',
  `company_address` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '单位地址',
  `company_postcode` varchar(10) DEFAULT NULL COMMENT '邮政编码',
  `company_industry` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '单位所属行业',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  `validate_status` int(11) DEFAULT '1' COMMENT '是否有效 1：是，2：否',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `org_id` varchar(100) DEFAULT NULL COMMENT '机构编码',
  `org_name` varchar(100) DEFAULT NULL COMMENT '机构名称',
  `import_batch_no` varchar(100) DEFAULT NULL COMMENT '导入批次号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17363 DEFAULT CHARSET=utf8 COMMENT='客户工作单位信息历史表';

-- ----------------------------
-- Table structure for t_lc_custinfo_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_custinfo_his`;
CREATE TABLE `t_lc_custinfo_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `custom_code` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户编号',
  `custom_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户姓名',
  `custom_sex` int(11) DEFAULT NULL COMMENT '客户性别 0：男1：女',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `certificate_type` int(11) DEFAULT NULL COMMENT '证件类型',
  `certificate_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '证件编号',
  `certificate_address` varchar(500) DEFAULT NULL,
  `profession` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '职业',
  `city` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '所在城市',
  `education` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '学历',
  `phone` varchar(50) DEFAULT NULL COMMENT '手机号',
  `tel` varchar(50) DEFAULT NULL COMMENT '家庭电话',
  `email` varchar(100) DEFAULT NULL COMMENT '电子邮件',
  `income_year` decimal(19,2) DEFAULT NULL COMMENT '年收入',
  `address` varchar(500) DEFAULT NULL,
  `marrage_status` int(11) DEFAULT NULL COMMENT '是否已婚 1：是，2：否',
  `has_child` int(11) DEFAULT NULL COMMENT '是否有孩 1：是，2：否',
  `has_house` int(11) DEFAULT NULL COMMENT '是否有房 1：是，2：否',
  `has_car` int(11) DEFAULT NULL COMMENT '是否有车 1：是，2：否',
  `validate_status` int(11) DEFAULT '1' COMMENT '是否有效 1：是，2：否',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  `org_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '所属机构',
  `org_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '机构名称',
  `census_address` varchar(500) DEFAULT NULL,
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `import_batch_no` varchar(100) DEFAULT NULL COMMENT '导入批次号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33762 DEFAULT CHARSET=utf8 COMMENT='客户信息历史表';

-- ----------------------------
-- Table structure for t_lc_duncase_action_record_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_duncase_action_record_his`;
CREATE TABLE `t_lc_duncase_action_record_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主鍵ID',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件号',
  `task_id` varchar(100) DEFAULT NULL COMMENT '任务编号',
  `repay_date` date DEFAULT NULL COMMENT '还款日期',
  `repay_amount` decimal(65,2) DEFAULT NULL COMMENT '还款金额',
  `recheck_date` date DEFAULT NULL COMMENT '复核日期',
  `recontact_date` datetime DEFAULT NULL COMMENT '再次联系时间',
  `action_code` varchar(100) DEFAULT NULL COMMENT '行动码',
  `remark` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '备注',
  `validate_status` int(11) DEFAULT '1' COMMENT '是否有效 1：是，2：否',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  KEY `case_no_index` (`case_no`)
) ENGINE=InnoDB AUTO_INCREMENT=300 DEFAULT CHARSET=utf8 COMMENT='案件行动码历史表';

-- ----------------------------
-- Table structure for t_lc_duncase_assign_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_duncase_assign_his`;
CREATE TABLE `t_lc_duncase_assign_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `custom_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户姓名',
  `certificate_no` varchar(100) DEFAULT NULL COMMENT '证件号',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `task_id` varchar(100) DEFAULT NULL COMMENT '任务编号',
  `operation_id` bigint(20) DEFAULT NULL COMMENT '操作员ID',
  `operation_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '操作员姓名',
  `transfer_type` int(11) DEFAULT NULL COMMENT '转移类型(0：初次导入，1：分派转移，2：委上转移，3：结案转移，4：协助催收，5：临时代理)',
  `task_status` int(11) DEFAULT NULL COMMENT '任务状态',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '业务归属人',
  `org_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '业务归属机构',
  `collect_team_id` varchar(10) DEFAULT NULL COMMENT '催收组ID',
  `collect_team_name` varchar(100) DEFAULT NULL COMMENT '催收组名称',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `validate_status` int(11) DEFAULT '1' COMMENT '是否有效 1：是，2：否',
  `remark` text COMMENT '备注',
  `owner_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '业务归属人名称',
  `org_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '所属机构名称',
  PRIMARY KEY (`id`),
  KEY `case_no_index` (`case_no`)
) ENGINE=InnoDB AUTO_INCREMENT=45683 DEFAULT CHARSET=utf8 COMMENT='案件轨迹历史表';

-- ----------------------------
-- Table structure for t_lc_duncase_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_duncase_his`;
CREATE TABLE `t_lc_duncase_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `custom_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户姓名',
  `certificate_no` varchar(100) DEFAULT NULL COMMENT '证件号码',
  `custom_phone` varchar(50) DEFAULT NULL,
  `month_repay_day` int(11) DEFAULT NULL COMMENT '账单日',
  `first_overdue_time` datetime DEFAULT NULL COMMENT '首次逾期时间',
  `overdue_days` bigint(11) DEFAULT NULL COMMENT '逾期天数',
  `overdue_aging` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '逾期账龄',
  `max_overdue_day` int(11) DEFAULT NULL COMMENT '历史最大逾期天数',
  `org_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '业务归属机构',
  `org_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '机构名称',
  `repay_date` date DEFAULT NULL COMMENT '应还日期',
  `borrow_line` decimal(13,2) DEFAULT NULL COMMENT '放款金额 ',
  `borrow_card_no` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '借款卡号',
  `borrow_bank` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '借款卡银行',
  `total_interest_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户应还利息总额',
  `total_principal_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户应还本金总额',
  `total_default_interest_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户应还罚息总额',
  `total_expenses_payable_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户应还费用总金额',
  `lowest_payment_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户最低应还金额',
  `total_debt_amount_rmb` decimal(13,2) DEFAULT NULL COMMENT '人民币账户欠款总金额',
  `appoint_case_balance` decimal(13,2) DEFAULT NULL COMMENT '委案余额即欠款总额',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  `transfer_type` varchar(10) DEFAULT NULL COMMENT '手别',
  `enter_coll_date` date DEFAULT NULL COMMENT '入催日',
  `close_case_yhje` decimal(13,2) DEFAULT NULL COMMENT '结案应还金额',
  `overdue_fine` decimal(13,2) DEFAULT NULL COMMENT '滞纳金',
  `city` varchar(255) DEFAULT NULL COMMENT '所属城市',
  `area` varchar(255) DEFAULT NULL COMMENT '所属区域',
  `recommend_vendor` varchar(255) DEFAULT NULL COMMENT '推荐商户',
  `recommend_website` varchar(255) DEFAULT NULL COMMENT '推荐网点',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `repay_method` varchar(255) DEFAULT NULL COMMENT '还款方式',
  `aging_periods` varchar(255) DEFAULT NULL COMMENT '分期期数',
  `bill_address` varchar(500) DEFAULT NULL,
  `year_interest_rate` varchar(255) DEFAULT NULL COMMENT '年利率',
  `day_interest_rate` varchar(255) DEFAULT NULL COMMENT '日利率',
  `first_overdue_sign` varchar(255) DEFAULT NULL COMMENT '首逾标识',
  `total_overdue_day` int(255) DEFAULT NULL COMMENT '累计逾期天数',
  `overdue_frequency` int(11) DEFAULT NULL COMMENT '逾期次数',
  `import_batch_no` varchar(50) DEFAULT NULL COMMENT '导入批次',
  `pack_no` varchar(100) DEFAULT NULL COMMENT '分发编号',
  `back_case_date` date DEFAULT NULL COMMENT '退案日',
  `loan_type` char(10) DEFAULT NULL COMMENT '贷款类型',
  `stay_case_flag` char(10) DEFAULT NULL COMMENT '留案标签',
  `risk_flag` char(10) DEFAULT NULL COMMENT '风险标签',
  `contract_type` char(10) DEFAULT NULL COMMENT '合同类型',
  `reduction_flag` char(10) DEFAULT NULL COMMENT '减免标签',
  `legal_flag` char(10) DEFAULT NULL COMMENT '法催标签',
  `ljyhje` decimal(20,2) DEFAULT NULL COMMENT '累计已还金额',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=50408 DEFAULT CHARSET=utf8 COMMENT='案件历史表';

-- ----------------------------
-- Table structure for t_lc_task_his
-- ----------------------------
DROP TABLE IF EXISTS `t_lc_task_his`;
CREATE TABLE `t_lc_task_his` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主鍵ID',
  `case_no` varchar(100) DEFAULT NULL COMMENT '案件编号',
  `certificate_no` varchar(100) DEFAULT NULL COMMENT '证件号',
  `certificate_type` int(11) DEFAULT NULL COMMENT '证件类型',
  `custom_code` varchar(100) DEFAULT NULL COMMENT '客户编号',
  `custom_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户姓名',
  `arrears_total` decimal(13,2) DEFAULT NULL COMMENT '委案金额',
  `task_status` int(11) DEFAULT NULL COMMENT '任务状态 1：未分配 2：催收中 3: 已结案',
  `overdue_days` bigint(11) DEFAULT NULL COMMENT '逾期天数',
  `overdue_aging` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '逾期账龄',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '业务归属人',
  `owner_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '业务归属人',
  `org_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '业务归属机构',
  `org_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '所属机构',
  `close_date` datetime DEFAULT NULL COMMENT '结案日期',
  `old_owner_id` bigint(20) DEFAULT NULL COMMENT '原先的业务归属人',
  `task_type` int(11) DEFAULT NULL COMMENT '任务类型1：初次生成(导入)，2：重新分派，3：临时代理，4：协助催收',
  `allot_type` int(11) DEFAULT NULL COMMENT '分配类型1：手动，2：委外，3：机器人，4：法催',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
  `modify_by` bigint(20) DEFAULT NULL COMMENT '修改人',
  `old_owner_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '原先的业务归属人名称(催收员)',
  `robot_task_id` bigint(20) DEFAULT NULL COMMENT '机器人任务id，当分配类型是机器人时必填',
  `robot_call_strategy_id` int(11) DEFAULT NULL COMMENT '机器人呼叫策略id',
  `transfer_type` varchar(10) DEFAULT NULL COMMENT '手别',
  `enter_coll_date` date DEFAULT NULL COMMENT '入催日',
  `close_case_yhje` decimal(13,2) DEFAULT NULL COMMENT '结案应还金额',
  `recently_allot_date` datetime DEFAULT NULL COMMENT '最近分配日期',
  `recently_follow_up_date` datetime DEFAULT NULL COMMENT '最近跟进时间',
  `hit_rule` varchar(10) DEFAULT NULL COMMENT '命中规则',
  `hit_rule_desc` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '命中规则描述',
  `distribution_strategy` varchar(10) DEFAULT NULL COMMENT '策略',
  `import_batch_no` varchar(50) DEFAULT NULL,
  `action_code` varchar(100) DEFAULT NULL COMMENT '行动码键值',
  `action_code_value` varchar(100) DEFAULT NULL COMMENT '行动码中文',
  `call_sign` varchar(100) DEFAULT NULL COMMENT '电话码键值',
  `call_sign_value` varchar(100) DEFAULT NULL COMMENT '电话码中文',
  `phone` varchar(50) DEFAULT NULL,
  `dqyhje` decimal(20,2) DEFAULT NULL COMMENT '当前已还金额',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3939964442895 DEFAULT CHARSET=utf8 COMMENT='任务历史表';
