
alter table t_lc_duncase add back_case_date date  DEFAULT NULL COMMENT '退案日';
alter table t_lc_duncase add loan_type char(10) DEFAULT NULL COMMENT '贷款类型';
alter table t_lc_duncase add stay_case_flag char(10) DEFAULT NULL COMMENT '留案标签';
alter table t_lc_duncase add risk_flag char(10) DEFAULT NULL COMMENT '风险标签';
alter table t_lc_duncase add contract_type char(10) DEFAULT NULL COMMENT '合同类型';
alter table t_lc_duncase add reduction_flag char(10) DEFAULT NULL COMMENT '减免标签';
alter table t_lc_duncase add legal_flag char(10) DEFAULT NULL COMMENT '法催标签';

-- ----------------------------
-- Table structure for t_lc_column_query
-- ----------------------------
-- DROP TABLE IF EXISTS `t_lc_column_query`;
-- CREATE TABLE `t_lc_column_query` (
--   `id` bigint(20) NOT NULL AUTO_INCREMENT,
--   `org_id` int(11) DEFAULT NULL COMMENT '委托方编码',
--   `org_name` varchar(50) DEFAULT NULL COMMENT '委托方名称',
--   `table_name` varchar(50) DEFAULT NULL COMMENT '表名',
--   `column_name` varchar(50) DEFAULT NULL COMMENT '字段名称',
--   `column_name_cn` varchar(50) DEFAULT NULL COMMENT '字段中文名',
--   `column_type` varchar(255) DEFAULT NULL COMMENT '字段类型',
--   `compare_method` varchar(255) DEFAULT NULL COMMENT '字段比较方式',
--   `column_value` varchar(4000) DEFAULT NULL COMMENT '字段值，当选择下拉框时，让用户填入值',
--   `create_by` int(11) DEFAULT NULL COMMENT '创建人',
--   `create_time` datetime DEFAULT NULL COMMENT '创建时间',
--   `modify_by` int(11) DEFAULT NULL,
--   `modify_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 菜单 SQL
-- insert into sys_menu (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('字段查询配置', '3', '2131', '/column/query', 'C', '0', 'column:query:view', '#', 'admin', NOW(), 'admin', NOW(), '字段查询配置菜单');

-- 按钮父菜单ID
-- SELECT @parentId := LAST_INSERT_ID();

-- 按钮 SQL
-- insert into sys_menu  (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('查询', @parentId, '1',  '#',  'F', '0', 'column:query:list',         '#', 'admin', NOW(), 'admin', NOW(), '');
--
-- insert into sys_menu  (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('新增', @parentId, '2',  '#',  'F', '0', 'column:query:add',          '#', 'admin', NOW(), 'admin', NOW(), '');
--
-- insert into sys_menu  (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('修改', @parentId, '3',  '#',  'F', '0', 'column:query:edit',         '#', 'admin', NOW(), 'admin', NOW(), '');
--
-- insert into sys_menu  (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('删除', @parentId, '4',  '#',  'F', '0', 'column:query:remove',       '#', 'admin', NOW(), 'admin', NOW(), '');
--
-- insert into sys_menu  (menu_name, parent_id, order_num, url, menu_type, visible, perms, icon, create_by, create_time, update_by, update_time, remark)
-- values('导出', @parentId, '5',  '#',  'F', '0', 'column:query:export',       '#', 'admin', NOW(), 'admin', NOW(), '');
--
-- INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('字段动态查询表', 'colume_query_table', '0', 'admin', '2020-05-26 18:00:37', '', NULL, '字段动态查询表');
-- INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('任务管理字段', 't_lc_task', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '任务管理字段');
-- INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('字段类型', 'column_query_compare_type', '0', 'admin', '2020-05-26 18:26:45', 'admin', '2020-05-27 13:53:14', '字段动态查询比较类型');
-- INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('案件综合查询字段', 't_lc_duncase', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '案件综合查询字段');
-- INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('机器人呼叫明细查询字段', 't_lc_robot_task', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '机器人呼叫明细查询字段');
--
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '任务管理', 't_lc_task', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:01:56', '', NULL, '任务管理');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '案件综合查询', 't_lc_duncase', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:03:10', '', NULL, '案件综合查询');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '委案金额', 'arrears_total', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:34', '', NULL, '委案金额');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '结案应还金额', 'close_case_yhje', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:56', '', NULL, '结案应还金额');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:23', '', NULL, '手别');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:50', '', NULL, '手机号');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('5', '业务归属人', 'owner_name', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:08', '', NULL, '业务归属人');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '最近电话码', 'call_sign', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:36', '', NULL, '最近电话码');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '最近行动码', 'action_code', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:59', '', NULL, '最近行动码');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:23', '', NULL, '任务类型');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('9', '入催日', 'enter_coll_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:42', '', NULL, '入催日');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '最近分配日期', 'recently_allot_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:00', '', NULL, '最近分配日期');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('11', '最近跟进时间', 'recently_follow_up_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:15', '', NULL, '最近跟进时间');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '数值区间', 'number_interval', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:27:14', '', NULL, '数值区间');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '日期区间', 'date_interval', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:27:39', '', NULL, '日期区间');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '字符串', 'string', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:28:03', '', NULL, '字符串');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '字典项', 'dict', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:28:31', '', NULL, '字典项');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '机器人呼叫明细查询', 't_lc_robot_task', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 13:54:26', '', NULL, '机器人呼叫明细查询');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '委案金额', 'arrears_total', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:34', '', NULL, '委案金额');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '结案应还金额', 'close_case_yhje', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:56', '', NULL, '结案应还金额');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:23', '', NULL, '手别');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:50', '', NULL, '手机号');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('5', '业务归属人', 'owner_name', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:08', '', NULL, '业务归属人');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '最近电话码', 'call_sign', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:36', '', NULL, '最近电话码');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '最近行动码', 'action_code', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:59', '', NULL, '最近行动码');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:23', '', NULL, '任务类型');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('9', '入催日', 'enter_coll_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:42', '', NULL, '入催日');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '最近分配日期', 'recently_allot_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:00', '', NULL, '最近分配日期');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('11', '最近跟进时间', 'recently_follow_up_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:15', '', NULL, '最近跟进时间');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '姓名', 'cur_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:08:51', '', NULL, '姓名');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '话术名称', 'speech_craft_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:09:35', '', NULL, '话术名称');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:10:35', '', NULL, '手别');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:11:16', '', NULL, '手机号');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '客户意向标签', 'result_value_alias', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:12:33', '', NULL, '客户意向标签');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '通话时长', 'call_len', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:13:15', '', NULL, '通话时长');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:15:09', '', NULL, '任务类型');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '业务归属人', 'owner_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:17:55', '', NULL, '业务归属人');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('12', '拨打结束时间', 'call_end_date', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:18:59', '', NULL, '拨打结束时间');
-- INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('13', '创建时间', 'create_time', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:19:19', '', NULL, '创建时间');

-- 电话码：
-- PTP:承诺还款,CYH:称已还,TP:谈判沟通,WCY:无诚意,HKKN:还款困难,ZG:转告,WRJT:无人接听,JJ:拒接,ZX:占线忙音,GJ:关机,GD:挂断,KH:空号,BZ:不在,WCR:无此人,WHY:无回应,SL:失联,R01:已接听,R02:无法接通,R03:主叫号码不可用,R04:停机,R05:主叫欠费,R06:呼损,R07:黑名单,R08:线路盲区

-- 行动码：
-- ALPA:已还款,CNHK:承诺还款,ZTGJ:暂停跟进,TS:投诉,NXT:未达成还款,DYZG:答应转告,ZCLX:再次联系

-- 任务类型：
-- 1:初次生成,2:重新分派,3:临时代理,4:协助催收,5:临时代理回收,7:结案转移,10:协助催收申请,11:停催申请,12:停止催收,13:停止催收激活,14:停止催收拒绝,15:拒绝协催,16:机器人协催,17:机器人拉回

-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'arrears_total', '委案金额', 'number_interval', NULL, NULL, '1', '2020-05-28 13:00:20', '1', '2020-05-28 13:00:20');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'close_case_yhje', '结案应还金额', 'number_interval', NULL, NULL, '1', '2020-05-28 13:01:07', '1', '2020-05-28 13:01:07');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'transfer_type', '手别', 'string', NULL, 'equal,like', '1', '2020-05-28 13:01:33', '1', '2020-05-28 13:01:33');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'phone', '手机号', 'string', NULL, 'equal', '1', '2020-05-28 13:01:57', '1', '2020-05-28 13:01:57');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'owner_name', '业务归属人', 'string', NULL, 'equal,like', '1', '2020-05-28 13:02:10', '1', '2020-05-28 13:02:10');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'call_sign', '最近电话码', 'dict', NULL, 'PTP:承诺还款,CYH:称已还,TP:谈判沟通,WCY:无诚意,HKKN:还款困难,ZG:转告,WRJT:无人接听,JJ:拒接,ZX:占线忙音,GJ:关机,GD:挂断,KH:空号,BZ:不在,WCR:无此人,WHY:无回应,SL:失联,R01:已接听,R02:无法接通,R03:主叫号码不可用,R04:停机,R05:主叫欠费,R06:呼损,R07:黑名单,R08:线路盲区', '1', '2020-05-28 13:08:44', '1', '2020-05-28 13:08:44');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'action_code', '最近行动码', 'dict', NULL, 'ALPA:已还款,CNHK:承诺还款,ZTGJ:暂停跟进,TS:投诉,NXT:未达成还款,DYZG:答应转告,ZCLX:再次联系', '1', '2020-05-28 13:10:49', '1', '2020-05-28 13:10:49');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'task_type', '任务类型', 'dict', NULL, '1:初次生成,2:重新分派,3:临时代理,4:协助催收,5:临时代理回收,7:结案转移,10:协助催收申请,11:停催申请,12:停止催收,13:停止催收激活,14:停止催收拒绝,15:拒绝协催,16:机器人协催,17:机器人拉回', '1', '2020-05-28 13:15:44', '1', '2020-05-28 13:15:44');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'enter_coll_date', '入催日', 'date_interval', NULL, NULL, '1', '2020-05-28 13:15:59', '1', '2020-05-28 13:15:59');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'recently_allot_date', '最近分配日期', 'date_interval', NULL, NULL, '1', '2020-05-28 13:16:11', '1', '2020-05-28 13:16:11');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_task', 'recently_follow_up_date', '最近跟进时间', 'date_interval', NULL, NULL, '1', '2020-05-28 13:16:20', '1', '2020-05-28 13:16:20');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'arrears_total', '委案金额', 'number_interval', NULL, NULL, '1', '2020-05-28 13:16:30', '1', '2020-05-28 13:16:30');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'close_case_yhje', '结案应还金额', 'number_interval', NULL, NULL, '1', '2020-05-28 13:16:40', '1', '2020-05-28 13:16:40');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'transfer_type', '手别', 'string', NULL, 'equal,like', '1', '2020-05-28 13:17:09', '1', '2020-05-28 13:17:09');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'phone', '手机号', 'string', NULL, 'equal', '1', '2020-05-28 13:17:29', '1', '2020-05-28 13:17:29');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'owner_name', '业务归属人', 'string', NULL, 'equal,like', '1', '2020-05-28 13:18:17', '1', '2020-05-28 13:18:17');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'call_sign', '最近电话码', 'dict', NULL, 'PTP:承诺还款,CYH:称已还,TP:谈判沟通,WCY:无诚意,HKKN:还款困难,ZG:转告,WRJT:无人接听,JJ:拒接,ZX:占线忙音,GJ:关机,GD:挂断,KH:空号,BZ:不在,WCR:无此人,WHY:无回应,SL:失联,R01:已接听,R02:无法接通,R03:主叫号码不可用,R04:停机,R05:主叫欠费,R06:呼损,R07:黑名单,R08:线路盲区', '1', '2020-05-28 13:18:41', '1', '2020-05-28 13:18:41');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'action_code', '最近行动码', 'dict', NULL, 'ALPA:已还款,CNHK:承诺还款,ZTGJ:暂停跟进,TS:投诉,NXT:未达成还款,DYZG:答应转告,ZCLX:再次联系', '1', '2020-05-28 13:19:01', '1', '2020-05-28 13:19:01');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'task_type', '任务类型', 'dict', NULL, '1:初次生成,2:重新分派,3:临时代理,4:协助催收,5:临时代理回收,7:结案转移,10:协助催收申请,11:停催申请,12:停止催收,13:停止催收激活,14:停止催收拒绝,15:拒绝协催,16:机器人协催,17:机器人拉回', '1', '2020-05-28 13:19:21', '1', '2020-05-28 13:19:21');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'enter_coll_date', '入催日', 'date_interval', NULL, NULL, '1', '2020-05-28 13:19:36', '1', '2020-05-28 13:19:36');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'recently_allot_date', '最近分配日期', 'date_interval', NULL, NULL, '1', '2020-05-28 13:19:47', '1', '2020-05-28 13:19:47');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_duncase', 'recently_follow_up_date', '最近跟进时间', 'date_interval', NULL, NULL, '1', '2020-05-28 13:19:57', '1', '2020-05-28 13:19:57');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'cur_name', '姓名', 'string', NULL, 'equal,like', '1', '2020-05-28 13:20:13', '1', '2020-05-28 13:20:13');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'speech_craft_name', '话术名称', 'dict', NULL, '测试话术:测试话术', '1', '2020-05-28 13:20:56', '1', '2020-05-28 13:20:56');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'transfer_type', '手别', 'string', NULL, 'equal,like', '1', '2020-05-28 13:21:10', '1', '2020-05-28 13:21:10');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'phone', '手机号', 'string', NULL, 'equal', '1', '2020-05-28 13:21:26', '1', '2020-05-28 13:21:26');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'result_value_alias', '客户意向标签', 'dict', NULL, 'A:A,B:B,C:C,D:D,E:E', '1', '2020-05-28 13:21:43', '1', '2020-05-28 13:21:43');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'call_len', '通话时长', 'number_interval', NULL, NULL, '1', '2020-05-28 13:21:55', '1', '2020-05-28 13:21:55');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'task_type', '任务类型', 'dict', NULL, '1:初次生成,2:重新分派,3:临时代理,4:协助催收,5:临时代理回收,7:结案转移,10:协助催收申请,11:停催申请,12:停止催收,13:停止催收激活,14:停止催收拒绝,15:拒绝协催,16:机器人协催,17:机器人拉回', '1', '2020-05-28 13:22:14', '1', '2020-05-28 13:22:14');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'owner_name', '业务归属人', 'string', NULL, 'equal,like', '1', '2020-05-28 13:22:30', '1', '2020-05-28 13:22:30');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'call_end_date', '拨打结束时间', 'date_interval', NULL, NULL, '1', '2020-05-28 13:22:40', '1', '2020-05-28 13:22:40');
-- INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `compare_method`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('214', '中投保催收项目', 't_lc_robot_task', 'create_time', '创建时间', 'date_interval', NULL, NULL, '1', '2020-05-28 13:22:50', '1', '2020-05-28 13:22:50');
