duyan:
  apikey: CzTAfTCxNdBUUXw7ZvpzwB48NxCBkO54
  tokenUrl: https://open.duyansoft.com/api/v1/account/login/cti
  logUrl: https://open.duyansoft.com/api/v1/call_log
  soundRecordingUrl: https://open.duyansoft.com/api/v1/call/recording
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 7443
  ssl:
    key-store: file:/usr/ssl/4389013_www.hdnuggets.cn.pfx
    key-store-password: 7RibIXk6
    keyStoreType: PKCS12
    key-alias: alias