alter table t_lc_report_day_process add user_cover_num int(5) DEFAULT NULL  COMMENT '覆盖账户数';
alter table t_lc_report_day_process add call_num int(5) DEFAULT NULL  COMMENT '拨打次数';
alter table t_lc_report_day_process add connected_call_num int(5) DEFAULT NULL  COMMENT '接通次数';

alter table t_lc_call_record add type int(2) default null comment '类型，1：打电话下电话码 2：未打电话直接下电话码3：导入催记电话码';


DROP TABLE IF EXISTS `t_lc_column_query`;
CREATE TABLE `t_lc_column_query` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `org_id` int(11) DEFAULT NULL COMMENT '委托方编码',
  `org_name` varchar(50) DEFAULT NULL COMMENT '委托方名称',
  `table_name` varchar(50) DEFAULT NULL COMMENT '表名',
  `column_name` varchar(50) DEFAULT NULL COMMENT '字段名称',
  `column_name_cn` varchar(50) DEFAULT NULL COMMENT '字段中文名',
  `column_type` varchar(255) DEFAULT NULL COMMENT '字段类型',
  `bean_name` varchar(255) DEFAULT NULL COMMENT '实体类字段',
  `column_value` varchar(4000) DEFAULT NULL COMMENT '字段值，当选择下拉框时，让用户填入值',
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `modify_by` int(11) DEFAULT NULL,
  `modify_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('字段动态查询表', 'colume_query_table', '0', 'admin', '2020-05-26 18:00:37', '', NULL, '字段动态查询表');
INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('任务管理字段', 't_lc_task', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '任务管理字段');
INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('字段类型', 'column_query_compare_type', '0', 'admin', '2020-05-26 18:26:45', 'admin', '2020-05-27 13:53:14', '字段动态查询比较类型');
INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('案件综合查询字段', 't_lc_duncase', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '案件综合查询字段');
INSERT INTO `sys_dict_type` (`dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('机器人呼叫明细查询字段', 't_lc_robot_task', '0', 'admin', '2020-05-26 18:04:39', 'admin', '2020-05-26 18:08:20', '机器人呼叫明细查询字段');

INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '任务管理', 't_lc_task', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:01:56', '', NULL, '任务管理');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '案件综合查询', 't_lc_duncase', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:03:10', '', NULL, '案件综合查询');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '机器人呼叫明细查询', 't_lc_robot_task', 'colume_query_table', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 13:54:26', '', NULL, '机器人呼叫明细查询');

INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '数值区间', 'number_interval', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:27:14', '', NULL, '数值区间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '日期区间', 'date_interval', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:27:39', '', NULL, '日期区间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '字符串', 'string', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:28:03', '', NULL, '字符串');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '字典项', 'dict', 'column_query_compare_type', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:28:31', '', NULL, '字典项');

INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '委案金额', 'arrears_total', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:34', '', NULL, '委案金额');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '结案应还金额', 'close_case_yhje', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:56', '', NULL, '结案应还金额');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:23', '', NULL, '手别');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:50', '', NULL, '手机号');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('5', '业务归属人', 'owner_name', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:08', '', NULL, '业务归属人');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '最近电话码', 'call_sign', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:36', '', NULL, '最近电话码');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '最近行动码', 'action_code', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:59', '', NULL, '最近行动码');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:23', '', NULL, '任务类型');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('9', '入催日', 'enter_coll_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:42', '', NULL, '入催日');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '最近分配日期', 'recently_allot_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:00', '', NULL, '最近分配日期');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('11', '最近跟进时间', 'recently_follow_up_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:15', '', NULL, '最近跟进时间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '委案金额', 'arrears_total', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:34', '', NULL, '委案金额');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '结案应还金额', 'close_case_yhje', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:09:56', '', NULL, '结案应还金额');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:23', '', NULL, '手别');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:10:50', '', NULL, '手机号');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('5', '业务归属人', 'owner_name', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:08', '', NULL, '业务归属人');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '最近电话码', 'call_sign', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:36', '', NULL, '最近电话码');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '最近行动码', 'action_code', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:11:59', '', NULL, '最近行动码');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:23', '', NULL, '任务类型');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('9', '入催日', 'enter_coll_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:12:42', '', NULL, '入催日');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '最近分配日期', 'recently_allot_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:00', '', NULL, '最近分配日期');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('11', '最近跟进时间', 'recently_follow_up_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-05-26 18:13:15', '', NULL, '最近跟进时间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('1', '姓名', 'cur_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:08:51', '', NULL, '姓名');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('2', '话术名称', 'speech_craft_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:09:35', '', NULL, '话术名称');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('3', '手别', 'transfer_type', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:10:35', '', NULL, '手别');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('4', '手机号', 'phone', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:11:16', '', NULL, '手机号');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('6', '客户意向标签', 'result_value_alias', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:12:33', '', NULL, '客户意向标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('7', '通话时长', 'call_len', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:13:15', '', NULL, '通话时长');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('8', '任务类型', 'task_type', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:15:09', '', NULL, '任务类型');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('10', '业务归属人', 'owner_name', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:17:55', '', NULL, '业务归属人');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('12', '拨打结束时间', 'call_end_date', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:18:59', '', NULL, '拨打结束时间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('13', '创建时间', 'create_time', 't_lc_robot_task', NULL, NULL, 'Y', '0', 'admin', '2020-05-27 14:19:19', '', NULL, '创建时间');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('12', '所属区域', 'area', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:50:02', '', NULL, '所属区域');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('13', '风险标签', 'risk_flag', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:50:33', '', NULL, '风险标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('14', '退案日', 'back_case_date', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:51:00', '', NULL, '退案日');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('15', '合同类型', 'contract_type', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:52:14', '', NULL, '合同类型');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('16', '减免标签', 'reduction_flag', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:52:48', '', NULL, '减免标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('17', '法催标签', 'legal_flag', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:53:11', '', NULL, '法催标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('18', '留案标签', 'stay_case_flag', 't_lc_task', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:53:42', '', NULL, '留案标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('12', '所属区域', 'area', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:50:02', '', NULL, '所属区域');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('13', '风险标签', 'risk_flag', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:50:33', '', NULL, '风险标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('14', '退案日', 'back_case_date', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:51:00', '', NULL, '退案日');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('15', '合同类型', 'contract_type', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:52:14', '', NULL, '合同类型');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('16', '减免标签', 'reduction_flag', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:52:48', '', NULL, '减免标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('17', '法催标签', 'legal_flag', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:53:11', '', NULL, '法催标签');
INSERT INTO `sys_dict_data` (`dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES ('18', '留案标签', 'stay_case_flag', 't_lc_duncase', NULL, NULL, 'Y', '0', 'admin', '2020-06-03 13:53:42', '', NULL, '留案标签');

INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'arrears_total', '委案金额', 'number_interval', 'startArrearsTotal|endArrearsTotal', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 10:28:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'phone', '手机号', 'string', 'phone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'appoint_case_balance', '委案金额', 'number_interval', 'startAppointCaseBalance|endAppointCaseBalance', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 17:30:50');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'custom_phone', '手机号', 'string', 'customPhone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_duncase', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'cur_name', '姓名', 'string', 'curName', NULL, '1', '2020-06-02 19:40:46', '1', '2020-06-02 19:40:46');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'speech_craft_name', '话术名称', 'dict', 'speechCraftName', '测试话术:测试话术', '1', '2020-06-02 19:42:49', '1', '2020-06-02 19:46:32');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'transfer_type', '手别', 'string', 'transferType', NULL, '1', '2020-06-02 19:43:53', '1', '2020-06-02 19:43:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'phone', '手机号', 'string', 'phone', NULL, '1', '2020-06-02 19:44:29', '1', '2020-06-02 19:44:29');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'result_value_alias', '客户意向标签', 'dict', 'resultValueAlias', 'A:A|B:B|C:C|D:D|E:E', '1', '2020-06-02 19:45:23', '1', '2020-06-02 19:51:54');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'call_len', '通话时长', 'number_interval', 'startCallLen|endCallLen', NULL, '1', '2020-06-02 19:47:37', '1', '2020-06-02 19:47:37');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 19:48:23', '1', '2020-06-02 19:52:08');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'owner_name', '业务归属人', 'string', 'ownerName', NULL, '1', '2020-06-02 19:48:47', '1', '2020-06-02 19:48:47');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'call_end_date', '拨打结束时间', 'date_interval', 'startCallEndDate|endCallEndDate', NULL, '1', '2020-06-02 19:50:00', '1', '2020-06-02 19:50:00');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '212', '捷信消金', 't_lc_robot_task', 'create_time', '创建时间', 'date_interval', 'startCreateTime|endCreateTime', NULL, '1', '2020-06-02 19:50:22', '1', '2020-06-02 19:50:22');

INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'area', '所属区域', 'string', 'area', NULL, '1', '2020-06-03 13:57:39', '1', '2020-06-03 13:57:39');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'risk_flag', '风险标签', 'string', 'riskFlag', NULL, '1', '2020-06-03 14:02:19', '1', '2020-06-03 14:02:19');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'back_case_date', '退案日', 'date_interval', 'startBackCaseDate|endBackCaseDate', NULL, '1', '2020-06-03 14:02:51', '1', '2020-06-03 14:02:51');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'contract_type', '合同类型', 'string', 'contractType', NULL, '1', '2020-06-03 14:04:26', '1', '2020-06-03 14:04:26');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'reduction_flag', '减免标签', 'string', 'reductionFlag', NULL, '1', '2020-06-03 14:05:59', '1', '2020-06-03 14:05:59');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'legal_flag', '法催标签', 'string', 'legalFlag', NULL, '1', '2020-06-03 14:06:29', '1', '2020-06-03 14:06:29');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_task', 'stay_case_flag', '留案标签', 'string', 'stayCaseFlag', NULL, '1', '2020-06-03 14:07:01', '1', '2020-06-03 14:07:01');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'area', '所属区域', 'string', 'area', NULL, '1', '2020-06-03 13:57:39', '1', '2020-06-03 13:57:39');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'risk_flag', '风险标签', 'string', 'riskFlag', NULL, '1', '2020-06-03 14:02:19', '1', '2020-06-03 14:02:19');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'back_case_date', '退案日', 'date_interval', 'startBackCaseDate|endBackCaseDate', NULL, '1', '2020-06-03 14:02:51', '1', '2020-06-03 14:02:51');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'contract_type', '合同类型', 'string', 'contractType', NULL, '1', '2020-06-03 14:04:26', '1', '2020-06-03 14:04:26');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'reduction_flag', '减免标签', 'string', 'reductionFlag', NULL, '1', '2020-06-03 14:05:59', '1', '2020-06-03 14:05:59');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'legal_flag', '法催标签', 'string', 'legalFlag', NULL, '1', '2020-06-03 14:06:29', '1', '2020-06-03 14:06:29');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('212', '捷信消金', 't_lc_duncase', 'stay_case_flag', '留案标签', 'string', 'stayCaseFlag', NULL, '1', '2020-06-03 14:07:01', '1', '2020-06-03 14:07:01');
-- 中银消金
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'arrears_total', '委案金额', 'number_interval', 'startArrearsTotal|endArrearsTotal', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 10:28:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'phone', '手机号', 'string', 'phone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_task', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_duncase', 'appoint_case_balance', '委案金额', 'number_interval', 'startAppointCaseBalance|endAppointCaseBalance', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 17:30:50');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('208', '中银消金', 't_lc_duncase', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'custom_phone', '手机号', 'string', 'customPhone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_duncase', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'cur_name', '姓名', 'string', 'curName', NULL, '1', '2020-06-02 19:40:46', '1', '2020-06-02 19:40:46');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'speech_craft_name', '话术名称', 'dict', 'speechCraftName', '测试话术:测试话术', '1', '2020-06-02 19:42:49', '1', '2020-06-02 19:46:32');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'transfer_type', '手别', 'string', 'transferType', NULL, '1', '2020-06-02 19:43:53', '1', '2020-06-02 19:43:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'phone', '手机号', 'string', 'phone', NULL, '1', '2020-06-02 19:44:29', '1', '2020-06-02 19:44:29');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'result_value_alias', '客户意向标签', 'dict', 'resultValueAlias', 'A:A|B:B|C:C|D:D|E:E', '1', '2020-06-02 19:45:23', '1', '2020-06-02 19:51:54');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'call_len', '通话时长', 'number_interval', 'startCallLen|endCallLen', NULL, '1', '2020-06-02 19:47:37', '1', '2020-06-02 19:47:37');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 19:48:23', '1', '2020-06-02 19:52:08');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'owner_name', '业务归属人', 'string', 'ownerName', NULL, '1', '2020-06-02 19:48:47', '1', '2020-06-02 19:48:47');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'call_end_date', '拨打结束时间', 'date_interval', 'startCallEndDate|endCallEndDate', NULL, '1', '2020-06-02 19:50:00', '1', '2020-06-02 19:50:00');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '208', '中银消金', 't_lc_robot_task', 'create_time', '创建时间', 'date_interval', 'startCreateTime|endCreateTime', NULL, '1', '2020-06-02 19:50:22', '1', '2020-06-02 19:50:22');

-- 中投保
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'arrears_total', '委案金额', 'number_interval', 'startArrearsTotal|endArrearsTotal', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 10:28:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'phone', '手机号', 'string', 'phone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_task', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_duncase', 'appoint_case_balance', '委案金额', 'number_interval', 'startAppointCaseBalance|endAppointCaseBalance', NULL, '1', '2020-06-02 09:50:19', '1', '2020-06-02 17:30:50');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ('211', '中投保（浦发银行）', 't_lc_duncase', 'close_case_yhje', '结案应还金额', 'number_interval', 'startCloseCaseYhje|endCloseCaseYhje', NULL, '1', '2020-06-02 09:50:42', '1', '2020-06-02 10:28:21');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'transfer_type', '手别', 'string', 'transferType', 'equal:等于|like:包含', '1', '2020-06-02 09:51:50', '1', '2020-06-02 13:41:05');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'custom_phone', '手机号', 'string', 'customPhone', 'equal:等于', '1', '2020-06-02 09:52:38', '1', '2020-06-02 13:41:07');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'owner_name', '业务归属人', 'string', 'ownerName', 'equal:等于|like:包含', '1', '2020-06-02 09:53:04', '1', '2020-06-02 13:41:13');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'call_sign', '最近电话码', 'dict', 'callCode', 'PTP:承诺还款|CYH:称已还|TP:谈判沟通|WCY:无诚意|HKKN:还款困难|ZG:转告|WRJT:无人接听|JJ:拒接|ZX:占线忙音|GJ:关机|GD:挂断|KH:空号|BZ:不在|WCR:无此人|WHY:无回应|SL:失联|R01:已接听|R02:无法接通|R03:主叫号码不可用|R04:停机|R05:主叫欠费|R06:呼损|R07:黑名单|R08:线路盲区', '1', '2020-06-02 09:54:06', '1', '2020-06-02 13:51:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'action_code', '最近行动码', 'dict', 'actionCode', 'ALPA:已还款|CNHK:承诺还款|ZTGJ:暂停跟进|TS:投诉|NXT:未达成还款|DYZG:答应转告|ZCLX:再次联系', '1', '2020-06-02 09:54:45', '1', '2020-06-02 13:52:16');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 09:55:28', '1', '2020-06-02 13:52:45');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'enter_coll_date', '入催日', 'date_interval', 'startEnterCollDate|endEnterCollDate', NULL, '1', '2020-06-02 09:56:46', '1', '2020-06-02 10:28:24');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'recently_allot_date', '最近分配日期', 'date_interval', 'startRecentlyAllotDate|endRecentlyAllotDate', NULL, '1', '2020-06-02 09:57:11', '1', '2020-06-02 10:28:28');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_duncase', 'recently_follow_up_date', '最近跟进时间', 'date_interval', 'startRecentlyFollowUpDate|endRecentlyFollowUpDate', NULL, '1', '2020-06-02 09:57:38', '1', '2020-06-02 10:28:34');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'cur_name', '姓名', 'string', 'curName', NULL, '1', '2020-06-02 19:40:46', '1', '2020-06-02 19:40:46');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'speech_craft_name', '话术名称', 'dict', 'speechCraftName', '测试话术:测试话术', '1', '2020-06-02 19:42:49', '1', '2020-06-02 19:46:32');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'transfer_type', '手别', 'string', 'transferType', NULL, '1', '2020-06-02 19:43:53', '1', '2020-06-02 19:43:53');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'phone', '手机号', 'string', 'phone', NULL, '1', '2020-06-02 19:44:29', '1', '2020-06-02 19:44:29');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'result_value_alias', '客户意向标签', 'dict', 'resultValueAlias', 'A:A|B:B|C:C|D:D|E:E', '1', '2020-06-02 19:45:23', '1', '2020-06-02 19:51:54');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'call_len', '通话时长', 'number_interval', 'startCallLen|endCallLen', NULL, '1', '2020-06-02 19:47:37', '1', '2020-06-02 19:47:37');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'task_type', '任务类型', 'dict', 'taskType', '1:初次生成|2:重新分派|3:临时代理|4:协助催收|5:临时代理回收|7:结案转移|10:协助催收申请|11:停催申请|12:停止催收|13:停止催收激活|14:停止催收拒绝|15:拒绝协催|16:机器人协催|17:机器人拉回', '1', '2020-06-02 19:48:23', '1', '2020-06-02 19:52:08');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'owner_name', '业务归属人', 'string', 'ownerName', NULL, '1', '2020-06-02 19:48:47', '1', '2020-06-02 19:48:47');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'call_end_date', '拨打结束时间', 'date_interval', 'startCallEndDate|endCallEndDate', NULL, '1', '2020-06-02 19:50:00', '1', '2020-06-02 19:50:00');
INSERT INTO `t_lc_column_query` (`org_id`, `org_name`, `table_name`, `column_name`, `column_name_cn`, `column_type`, `bean_name`, `column_value`, `create_by`, `create_time`, `modify_by`, `modify_time`) VALUES ( '211', '中投保（浦发银行）', 't_lc_robot_task', 'create_time', '创建时间', 'date_interval', 'startCreateTime|endCreateTime', NULL, '1', '2020-06-02 19:50:22', '1', '2020-06-02 19:50:22');

