alter table cur_assets_package drop column twentyFourCD;
alter table cur_assets_package drop column BLK;
alter table cur_assets_package drop column productLine;
alter table cur_assets_package drop column rmb_last_jkje;
alter table cur_assets_package drop column rmb_cd;
alter table cur_assets_package drop column rmb_zhycjkr;
alter table cur_assets_package drop column rmb_zhhkbs;
alter table cur_assets_package drop column rmb_yhbj1;
alter table cur_assets_package drop column rmb_yhbj2;
alter table cur_assets_package drop column rmb_yhfx1;
alter table cur_assets_package drop column rmb_yhfx2;
alter table cur_assets_package drop column rmb_yhfy1;
alter table cur_assets_package drop column rmb_yhfy2;
alter table cur_assets_package drop column rmb_gded;
alter table cur_assets_package drop column code;
alter table cur_assets_package drop column zx_type;
alter table cur_assets_package drop column stop_card;
alter table cur_assets_package drop column stop_jxrq;
alter table cur_assets_package drop column cs_company;
alter table cur_assets_package drop column gz_flag;
alter table cur_assets_package drop column fq_flag;
alter table cur_assets_package drop column syhx_qtfy;
alter table cur_assets_package drop column syhx_sxf;
alter table cur_assets_package drop column syhx_bj;
alter table cur_assets_package drop column syhx_znf;
alter table cur_assets_package drop column syhx_yqx;
alter table cur_assets_package drop column syhx_jehj;
alter table cur_assets_package drop column cs_remark_his;
alter table cur_assets_package drop column csjggs_his;
alter table cur_assets_package drop column qx_flag;
alter table cur_assets_package drop column st_company;
alter table cur_assets_package drop column accept_firm;
alter table cur_assets_package drop column accept_city;
alter table cur_assets_package drop column accept_wd;
alter table cur_assets_package drop column accept_wd_code;
alter table cur_assets_package drop column dzhxrq;
alter table cur_assets_package drop column remark;
alter table cur_assets_package drop column wb_yhfxze;
alter table cur_assets_package drop column wb_yhlxze;
alter table cur_assets_package drop column wb_yhbj1;
alter table cur_assets_package drop column wb_yhbj2;
alter table cur_assets_package drop column wb_yhbjzje;
alter table cur_assets_package drop column wb_yhfx1;
alter table cur_assets_package drop column wb_yhfx2;
alter table cur_assets_package drop column wb_yhfy1;
alter table cur_assets_package drop column wb_yhfy2;
alter table cur_assets_package drop column wb_yhfyze;
alter table cur_assets_package drop column wb_zdyhe;
alter table cur_assets_package drop column wb_qkzje;
alter table cur_assets_package drop column tx_flag;
alter table cur_assets_package drop column ww_company_code;
alter table cur_assets_package drop column ww_jh_enddate;
alter table cur_assets_package drop column ww_qsrq;
alter table cur_assets_package drop column ww_pc;
alter table cur_assets_package drop column bill_address_postcode;
alter table cur_assets_package drop column yhk_date;
alter table cur_assets_package drop column start_yq_date;
alter table cur_assets_package drop column kh_date;
alter table cur_assets_package drop column ts_flag;
alter table cur_assets_package drop column credit_value;
alter table cur_assets_package drop column tj_city;
alter table cur_assets_package drop column shhx_sxf;
alter table cur_assets_package drop column shhx_bj;
alter table cur_assets_package drop column shhx_znf;
alter table cur_assets_package drop column shhx_fy;
alter table cur_assets_package drop column shhx_yqx;
alter table cur_assets_package drop column shhx_jehj;
alter table cur_assets_package drop column zh_30_day;
alter table cur_assets_package drop column zh_x_day;
alter table cur_assets_package drop column is_zc;
alter table cur_assets_package drop column is_zwcz;
alter table cur_assets_package drop column is_jx;
alter table cur_assets_package drop column is_sx;
alter table cur_assets_package drop column zjyq_month;
alter table cur_assets_package drop column hx_sxfcs;
alter table cur_assets_package drop column hx_shzt;
alter table cur_assets_package drop column hx_bjcs;
alter table cur_assets_package drop column hx_znfcs;
alter table cur_assets_package drop column hx_fycs;
alter table cur_assets_package drop column hx_yqlxcs;
alter table cur_assets_package drop column hx_jehjcs;
alter table cur_assets_package drop column aj_hz_date;
alter table cur_assets_package drop column xfjzzh;
alter table cur_assets_package drop column tsaj_type;
alter table cur_assets_package drop column tj_date;
alter table cur_assets_package drop column dollar_ye;
alter table cur_assets_package drop column dollar_CD;
alter table cur_assets_package drop column dollar_zdyjkje;
alter table cur_assets_package drop column dollar_zhycjkr;
alter table cur_assets_package drop column dollar_zhycjkje;
alter table cur_assets_package drop column dollar_hkrhkbs;
alter table cur_assets_package drop column hkfs;
alter table cur_assets_package drop column hkqd;
alter table cur_assets_package drop column xwpf;
alter table cur_assets_package drop column account_yebj;
alter table cur_assets_package drop column account_jqrq;
alter table cur_assets_package drop column fzzb;
alter table cur_assets_package drop column revert_card_no;
alter table cur_assets_package drop column revert_card_blank;
alter table cur_assets_package drop column jjqd;
alter table cur_assets_package drop column overdue_flag;
alter table cur_assets_package drop column cwcs;
alter table cur_assets_package drop column quota_product;
alter table cur_assets_package drop column quota_code;
alter table cur_assets_package drop column quota_date;
alter table cur_assets_package drop column risk;
alter table cur_assets_package drop column first_fk_date;
alter table cur_assets_package drop column certificate_type;
alter table cur_assets_package drop column birthday;
alter table cur_assets_package drop column city;
alter table cur_assets_package drop column economy;
alter table cur_assets_package drop column cur_income;
alter table cur_assets_package drop column new_address;
alter table cur_assets_package drop column customer_no;
alter table cur_assets_package drop column customer_home_postcode;
alter table cur_assets_package drop column card_post_address;
alter table cur_assets_package drop column job;
alter table cur_assets_package drop column dept_name;
alter table cur_assets_package drop column indust;
alter table cur_assets_package drop column work_postcode;
alter table cur_assets_package drop column sjrq;
alter table cur_assets_package drop column hth ;
alter table cur_assets_package drop column jjh ;
alter table cur_assets_package drop column dqsyb_yj;
alter table cur_assets_package drop column dqsyb_ej;
alter table cur_assets_package drop column csjd;
alter table cur_assets_package drop column wbjb;
alter table cur_assets_package drop column ys_khjlmc ;
alter table cur_assets_package drop column khjlmc ;
alter table cur_assets_package drop column xfldycpmc;
alter table cur_assets_package drop column qxrq;
alter table cur_assets_package drop column dqrq;
alter table cur_assets_package drop column dkye;
alter table cur_assets_package drop column wbbs ;
alter table cur_assets_package drop column yqje;
alter table cur_assets_package drop column yqbj;
alter table cur_assets_package drop column yqlx;
alter table cur_assets_package drop column yqsxf;
alter table cur_assets_package drop column qdmc;
alter table cur_assets_package drop column wbsb;
alter table cur_assets_package drop column wbqs;
alter table cur_assets_package drop column fpsj;
alter table cur_assets_package drop column Expand1;
alter table cur_assets_package drop column Expand2;
alter table cur_assets_package drop column Expand3;
alter table cur_assets_package drop column Expand4;
alter table cur_assets_package drop column Expand5;
alter table cur_assets_package drop column Expand6;
alter table cur_assets_package drop column Expand7;
alter table cur_assets_package drop column Expand8;
alter table cur_assets_package drop column Expand9;
alter table cur_assets_package drop column Expand10;
alter table cur_assets_package drop column Expand11;
alter table cur_assets_package drop column Expand12;
alter table cur_assets_package drop column Expand13;
alter table cur_assets_package drop column Expand14;
alter table cur_assets_package drop column Expand15;
alter table cur_assets_package drop column Expand16;
alter table cur_assets_package drop column Expand17;
alter table cur_assets_package drop column Expand18;
alter table cur_assets_package drop column Expand19;
alter table cur_assets_package drop column Expand20;

alter table cur_assets_package add column account_age varchar(64) DEFAULT NULL COMMENT '账龄';
alter table cur_assets_package add column la_flag varchar(20) DEFAULT NULL COMMENT '留案标签';
alter table cur_assets_package add column fx_flag varchar(20) DEFAULT NULL COMMENT '风险标签';
alter table cur_assets_package add column htlx varchar(20) DEFAULT NULL COMMENT '合同类型';
alter table cur_assets_package add column jmbq varchar(20) DEFAULT NULL COMMENT '减免标签';
alter table cur_assets_package add column fcbq varchar(20) DEFAULT NULL COMMENT '法催标签';
alter table cur_assets_package add column fxsfbh varchar(20) DEFAULT NULL COMMENT '罚息是否变化';
alter table cur_assets_package add column remark varchar(255) DEFAULT NULL COMMENT '备注';
alter table cur_assets_package add column tar date DEFAULT NULL COMMENT '退案日';
alter table cur_assets_package add column jkrq date DEFAULT NULL COMMENT '借款日期';
alter table cur_assets_package add column zhychkr date DEFAULT NULL COMMENT '最近一次还款日';
alter table cur_assets_package add column mqhkje decimal(20,2) DEFAULT NULL COMMENT '每期还款金额';
alter table cur_assets_package add column dqqkje decimal(20,2) DEFAULT NULL COMMENT '当期欠款金额';
alter table cur_assets_package add column ljyhje decimal(20,2) DEFAULT NULL COMMENT '累计已还金额';
alter table cur_assets_package add column sfje decimal(20,2) DEFAULT NULL COMMENT '首付金额';
alter table cur_assets_package add column zdhkzh1 varchar(64) DEFAULT NULL COMMENT '指定还款账号1';
alter table cur_assets_package add column zdhkzh2 varchar(64) DEFAULT NULL COMMENT '指定还款账号2';
alter table cur_assets_package add column zdhkzhhm1 varchar(64) DEFAULT NULL COMMENT '指定还款账户户名1';
alter table cur_assets_package add column zdhkzhhm2 varchar(64) DEFAULT NULL COMMENT '指定还款账户户名2';
alter table cur_assets_package add column zdhkqd1 varchar(64) DEFAULT NULL COMMENT '指定还款渠道1';
alter table cur_assets_package add column zdhkqd2 varchar(64) DEFAULT NULL COMMENT '指定还款渠道2';
alter table cur_assets_package add column khmb varchar(64) DEFAULT NULL COMMENT '考核目标';
alter table cur_assets_package add column spjg decimal(20,2) DEFAULT NULL COMMENT '商品价格';
alter table cur_assets_package add column dklx varchar(20) DEFAULT NULL COMMENT '贷款类型';
alter table cur_assets_package add column jkbs varchar(20) DEFAULT NULL COMMENT '借款笔数';
alter table cur_assets_package add column spxx varchar(128) DEFAULT NULL COMMENT '商品信息';
alter table cur_assets_package add column wacs varchar(20) DEFAULT NULL COMMENT '委案次数';
alter table cur_assets_package add column ykqs varchar(20) DEFAULT NULL COMMENT '已还期数';
alter table cur_assets_package add column work_dept varchar(64) DEFAULT NULL COMMENT '工作部门';
alter table cur_assets_package add column customer_mobile2 varchar(64) DEFAULT NULL COMMENT '客户电话2';
alter table cur_assets_package add column customer_mobile3 varchar(64) DEFAULT NULL COMMENT '客户电话3';
alter table cur_assets_package add column customer_mobile4 varchar(64) DEFAULT NULL COMMENT '客户电话4';
alter table cur_assets_package add column fourth_liaison_name varchar(64) DEFAULT NULL COMMENT '联系人4姓名';
alter table cur_assets_package add column fourth_liaison_relation varchar(64) DEFAULT NULL COMMENT '联系人4关系';
alter table cur_assets_package add column fourth_liaison_mobile varchar(64) DEFAULT NULL COMMENT '联系人4电话';
alter table cur_assets_package add column fifth_liaison_name varchar(64) DEFAULT NULL COMMENT '联系人5姓名';
alter table cur_assets_package add column fifth_liaison_relation varchar(64) DEFAULT NULL COMMENT '联系人5关系';
alter table cur_assets_package add column fifth_liaison_mobile varchar(64) DEFAULT NULL COMMENT '联系人5电话';





alter table cur_assets_package_temp drop column twentyFourCD;
alter table cur_assets_package_temp drop column BLK;
alter table cur_assets_package_temp drop column productLine;
alter table cur_assets_package_temp drop column rmb_last_jkje;
alter table cur_assets_package_temp drop column rmb_cd;
alter table cur_assets_package_temp drop column rmb_zhycjkr;
alter table cur_assets_package_temp drop column rmb_zhhkbs;
alter table cur_assets_package_temp drop column rmb_yhbj1;
alter table cur_assets_package_temp drop column rmb_yhbj2;
alter table cur_assets_package_temp drop column rmb_yhfx1;
alter table cur_assets_package_temp drop column rmb_yhfx2;
alter table cur_assets_package_temp drop column rmb_yhfy1;
alter table cur_assets_package_temp drop column rmb_yhfy2;
alter table cur_assets_package_temp drop column rmb_gded;
alter table cur_assets_package_temp drop column code;
alter table cur_assets_package_temp drop column zx_type;
alter table cur_assets_package_temp drop column stop_card;
alter table cur_assets_package_temp drop column stop_jxrq;
alter table cur_assets_package_temp drop column cs_company;
alter table cur_assets_package_temp drop column gz_flag;
alter table cur_assets_package_temp drop column fq_flag;
alter table cur_assets_package_temp drop column syhx_qtfy;
alter table cur_assets_package_temp drop column syhx_sxf;
alter table cur_assets_package_temp drop column syhx_bj;
alter table cur_assets_package_temp drop column syhx_znf;
alter table cur_assets_package_temp drop column syhx_yqx;
alter table cur_assets_package_temp drop column syhx_jehj;
alter table cur_assets_package_temp drop column cs_remark_his;
alter table cur_assets_package_temp drop column csjggs_his;
alter table cur_assets_package_temp drop column qx_flag;
alter table cur_assets_package_temp drop column st_company;
alter table cur_assets_package_temp drop column accept_firm;
alter table cur_assets_package_temp drop column accept_city;
alter table cur_assets_package_temp drop column accept_wd;
alter table cur_assets_package_temp drop column accept_wd_code;
alter table cur_assets_package_temp drop column dzhxrq;
alter table cur_assets_package_temp drop column remark;
alter table cur_assets_package_temp drop column wb_yhfxze;
alter table cur_assets_package_temp drop column wb_yhlxze;
alter table cur_assets_package_temp drop column wb_yhbj1;
alter table cur_assets_package_temp drop column wb_yhbj2;
alter table cur_assets_package_temp drop column wb_yhbjzje;
alter table cur_assets_package_temp drop column wb_yhfx1;
alter table cur_assets_package_temp drop column wb_yhfx2;
alter table cur_assets_package_temp drop column wb_yhfy1;
alter table cur_assets_package_temp drop column wb_yhfy2;
alter table cur_assets_package_temp drop column wb_yhfyze;
alter table cur_assets_package_temp drop column wb_zdyhe;
alter table cur_assets_package_temp drop column wb_qkzje;
alter table cur_assets_package_temp drop column tx_flag;
alter table cur_assets_package_temp drop column ww_company_code;
alter table cur_assets_package_temp drop column ww_jh_enddate;
alter table cur_assets_package_temp drop column ww_qsrq;
alter table cur_assets_package_temp drop column ww_pc;
alter table cur_assets_package_temp drop column bill_address_postcode;
alter table cur_assets_package_temp drop column yhk_date;
alter table cur_assets_package_temp drop column start_yq_date;
alter table cur_assets_package_temp drop column kh_date;
alter table cur_assets_package_temp drop column ts_flag;
alter table cur_assets_package_temp drop column credit_value;
alter table cur_assets_package_temp drop column tj_city;
alter table cur_assets_package_temp drop column shhx_sxf;
alter table cur_assets_package_temp drop column shhx_bj;
alter table cur_assets_package_temp drop column shhx_znf;
alter table cur_assets_package_temp drop column shhx_fy;
alter table cur_assets_package_temp drop column shhx_yqx;
alter table cur_assets_package_temp drop column shhx_jehj;
alter table cur_assets_package_temp drop column zh_30_day;
alter table cur_assets_package_temp drop column zh_x_day;
alter table cur_assets_package_temp drop column is_zc;
alter table cur_assets_package_temp drop column is_zwcz;
alter table cur_assets_package_temp drop column is_jx;
alter table cur_assets_package_temp drop column is_sx;
alter table cur_assets_package_temp drop column zjyq_month;
alter table cur_assets_package_temp drop column hx_sxfcs;
alter table cur_assets_package_temp drop column hx_shzt;
alter table cur_assets_package_temp drop column hx_bjcs;
alter table cur_assets_package_temp drop column hx_znfcs;
alter table cur_assets_package_temp drop column hx_fycs;
alter table cur_assets_package_temp drop column hx_yqlxcs;
alter table cur_assets_package_temp drop column hx_jehjcs;
alter table cur_assets_package_temp drop column aj_hz_date;
alter table cur_assets_package_temp drop column xfjzzh;
alter table cur_assets_package_temp drop column tsaj_type;
alter table cur_assets_package_temp drop column tj_date;
alter table cur_assets_package_temp drop column dollar_ye;
alter table cur_assets_package_temp drop column dollar_CD;
alter table cur_assets_package_temp drop column dollar_zdyjkje;
alter table cur_assets_package_temp drop column dollar_zhycjkr;
alter table cur_assets_package_temp drop column dollar_zhycjkje;
alter table cur_assets_package_temp drop column dollar_hkrhkbs;
alter table cur_assets_package_temp drop column hkfs;
alter table cur_assets_package_temp drop column hkqd;
alter table cur_assets_package_temp drop column xwpf;
alter table cur_assets_package_temp drop column account_yebj;
alter table cur_assets_package_temp drop column account_jqrq;
alter table cur_assets_package_temp drop column fzzb;
alter table cur_assets_package_temp drop column revert_card_no;
alter table cur_assets_package_temp drop column revert_card_blank;
alter table cur_assets_package_temp drop column jjqd;
alter table cur_assets_package_temp drop column overdue_flag;
alter table cur_assets_package_temp drop column cwcs;
alter table cur_assets_package_temp drop column quota_product;
alter table cur_assets_package_temp drop column quota_code;
alter table cur_assets_package_temp drop column quota_date;
alter table cur_assets_package_temp drop column risk;
alter table cur_assets_package_temp drop column first_fk_date;
alter table cur_assets_package_temp drop column certificate_type;
alter table cur_assets_package_temp drop column birthday;
alter table cur_assets_package_temp drop column city;
alter table cur_assets_package_temp drop column economy;
alter table cur_assets_package_temp drop column cur_income;
alter table cur_assets_package_temp drop column new_address;
alter table cur_assets_package_temp drop column customer_no;
alter table cur_assets_package_temp drop column customer_home_postcode;
alter table cur_assets_package_temp drop column card_post_address;
alter table cur_assets_package_temp drop column job;
alter table cur_assets_package_temp drop column dept_name;
alter table cur_assets_package_temp drop column indust;
alter table cur_assets_package_temp drop column work_postcode;
alter table cur_assets_package_temp drop column sjrq;
alter table cur_assets_package_temp drop column hth ;
alter table cur_assets_package_temp drop column jjh ;
alter table cur_assets_package_temp drop column dqsyb_yj;
alter table cur_assets_package_temp drop column dqsyb_ej;
alter table cur_assets_package_temp drop column csjd;
alter table cur_assets_package_temp drop column wbjb;
alter table cur_assets_package_temp drop column ys_khjlmc ;
alter table cur_assets_package_temp drop column khjlmc ;
alter table cur_assets_package_temp drop column xfldycpmc;
alter table cur_assets_package_temp drop column qxrq;
alter table cur_assets_package_temp drop column dqrq;
alter table cur_assets_package_temp drop column dkye;
alter table cur_assets_package_temp drop column wbbs ;
alter table cur_assets_package_temp drop column yqje;
alter table cur_assets_package_temp drop column yqbj;
alter table cur_assets_package_temp drop column yqlx;
alter table cur_assets_package_temp drop column yqsxf;
alter table cur_assets_package_temp drop column qdmc;
alter table cur_assets_package_temp drop column wbsb;
alter table cur_assets_package_temp drop column wbqs;
alter table cur_assets_package_temp drop column fpsj;

alter table cur_assets_package_temp add column account_age varchar(64) DEFAULT NULL COMMENT '账龄';
alter table cur_assets_package_temp add column la_flag varchar(20) DEFAULT NULL COMMENT '留案标签';
alter table cur_assets_package_temp add column fx_flag varchar(20) DEFAULT NULL COMMENT '风险标签';
alter table cur_assets_package_temp add column htlx varchar(20) DEFAULT NULL COMMENT '合同类型';
alter table cur_assets_package_temp add column jmbq varchar(20) DEFAULT NULL COMMENT '减免标签';
alter table cur_assets_package_temp add column fcbq varchar(20) DEFAULT NULL COMMENT '法催标签';
alter table cur_assets_package_temp add column fxsfbh varchar(20) DEFAULT NULL COMMENT '罚息是否变化';
alter table cur_assets_package_temp add column remark varchar(255) DEFAULT NULL COMMENT '备注';
alter table cur_assets_package_temp add column tar varchar(64) DEFAULT NULL COMMENT '退案日';
alter table cur_assets_package_temp add column jkrq varchar(64) DEFAULT NULL COMMENT '借款日期';
alter table cur_assets_package_temp add column zhychkr varchar(64) DEFAULT NULL COMMENT '最近一次还款日';
alter table cur_assets_package_temp add column mqhkje varchar(64) DEFAULT NULL COMMENT '每期还款金额';
alter table cur_assets_package_temp add column dqqkje varchar(64) DEFAULT NULL COMMENT '当期欠款金额';
alter table cur_assets_package_temp add column ljyhje varchar(64) DEFAULT NULL COMMENT '累计已还金额';
alter table cur_assets_package_temp add column sfje varchar(64) DEFAULT NULL COMMENT '首付金额';
alter table cur_assets_package_temp add column zdhkzh1 varchar(64) DEFAULT NULL COMMENT '指定还款账号1';
alter table cur_assets_package_temp add column zdhkzh2 varchar(64) DEFAULT NULL COMMENT '指定还款账号2';
alter table cur_assets_package_temp add column zdhkzhhm1 varchar(64) DEFAULT NULL COMMENT '指定还款账户户名1';
alter table cur_assets_package_temp add column zdhkzhhm2 varchar(64) DEFAULT NULL COMMENT '指定还款账户户名2';
alter table cur_assets_package_temp add column zdhkqd1 varchar(64) DEFAULT NULL COMMENT '指定还款渠道1';
alter table cur_assets_package_temp add column zdhkqd2 varchar(64) DEFAULT NULL COMMENT '指定还款渠道2';
alter table cur_assets_package_temp add column khmb varchar(64) DEFAULT NULL COMMENT '考核目标';
alter table cur_assets_package_temp add column spjg varchar(64) DEFAULT NULL COMMENT '商品价格';
alter table cur_assets_package_temp add column dklx varchar(20) DEFAULT NULL COMMENT '贷款类型';
alter table cur_assets_package_temp add column jkbs varchar(20) DEFAULT NULL COMMENT '借款笔数';
alter table cur_assets_package_temp add column spxx varchar(128) DEFAULT NULL COMMENT '商品信息';
alter table cur_assets_package_temp add column wacs varchar(20) DEFAULT NULL COMMENT '委案次数';
alter table cur_assets_package_temp add column ykqs varchar(20) DEFAULT NULL COMMENT '已还期数';
alter table cur_assets_package_temp add column work_dept varchar(64) DEFAULT NULL COMMENT '工作部门';
alter table cur_assets_package_temp add column customer_mobile2 varchar(64) DEFAULT NULL COMMENT '客户电话2';
alter table cur_assets_package_temp add column customer_mobile3 varchar(64) DEFAULT NULL COMMENT '客户电话3';
alter table cur_assets_package_temp add column customer_mobile4 varchar(64) DEFAULT NULL COMMENT '客户电话4';
alter table cur_assets_package_temp add column fourth_liaison_name varchar(64) DEFAULT NULL COMMENT '联系人4姓名';
alter table cur_assets_package_temp add column fourth_liaison_relation varchar(64) DEFAULT NULL COMMENT '联系人4关系';
alter table cur_assets_package_temp add column fourth_liaison_mobile varchar(64) DEFAULT NULL COMMENT '联系人4电话';
alter table cur_assets_package_temp add column fifth_liaison_name varchar(64) DEFAULT NULL COMMENT '联系人5姓名';
alter table cur_assets_package_temp add column fifth_liaison_relation varchar(64) DEFAULT NULL COMMENT '联系人5关系';
alter table cur_assets_package_temp add column fifth_liaison_mobile varchar(64) DEFAULT NULL COMMENT '联系人5电话';




-- alter table t_lc_call_record add column agent_name varchar(64) DEFAULT NULL COMMENT '坐席名称';



